GET http://localhost:5001/tasks

###

GET http://localhost:5001/tasks/66f1e579e3eb97a4622cc733

###

POST http://localhost:5001/tasks
Content-Type: application/json

{
    "taskName": "test",
    "taskDescription": "test example"
}

###
DELETE http://localhost:5001/tasks/66f32d4236ae9285aca45d8e

###
PATCH http://localhost:5001/tasks/66f333f5f457be7098331501
Content-Type: application/json

{
    "taskName": "newTest"
   
}